
version: '3'
services:
  central_user_database:
    build: ./CentralUserDatabase/
    ports:
     - "5432:5432"
    volumes:
      - C:/Users/Daniel/Desktop:/var/lib/postgresql/data
  load_balancer:
   build: ./LoadBalancer/
   ports:
     - "80:80"
   restart: always
   platform: linux/amd64
  application_server:
    build: ./ApplicationServer/
#    ports:
#      - "81:8080"
